---
name: feedGnuplot
version: 1.00
author:
  - 'Dima Kogan <dkogan@cds.caltech.edu>'
abstract: A pipe-oriented frontend to Gnuplot
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::Script::Run: 0
configure_requires:
  Module::Build: 0.340201
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
